name: Java CI/CD Pipeline

# Триггер для запуска workflow
on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании pull request в ветку main

jobs:
  build:
    # Указываем, что эта работа будет выполняться на Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3  # Используем официальную GitHub Action для клонирования репозитория

      # Шаг 2: Настроим Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Указываем версию JDK для нашего проекта
          distribution: 'temurin'

      # Шаг 3: Устанавливаем зависимость JUnit
      - name: Download JUnit Platform Console
        run: |
          mkdir -p lib
          curl -L -o lib/junit-platform-console-standalone-1.10.0.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar

      # Шаг 4: Запуск вашего build.bat
      - name: Run build and tests
        run: |
          chmod +x build.bat
          ./build.bat

