name: Java CI/CD Pipeline

# Триггер для запуска workflow
on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Работаем на Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3  # Используем официальный action для клонирования репозитория

      # Шаг 2: Настроим Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Указываем, что хотим использовать JDK 17
          distribution: 'temurin'  # Указываем, что используем темпоральный JDK

      # Шаг 3: Устанавливаем зависимость JUnit
      - name: Install JUnit dependency
        run: |
          mkdir -p lib  # Создаем папку для библиотек
          curl -L -o lib/junit-platform-console-standalone-1.10.0.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar

      # Шаг 4: Сборка и запуск тестов с помощью javac
      - name: Build and Test with javac
        run: |
          # Компилируем основной код и тесты
          javac -cp "lib/junit-platform-console-standalone-1.10.0.jar:src/main/java" src/main/java/com/example/App.java src/test/java/com/example/AppTest.java

          # Запускаем тесты с использованием JUnit
          java -cp "lib/junit-platform-console-standalone-1.10.0.jar:src/main/java" org.junit.platform.console.ConsoleLauncher --scan-classpath


